packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  "@scarf/scarf": false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - brace-expansion@1.1.16 || 2.1.2
overrides:
  brace-expansion@<1.1.16: ^1.1.16
  brace-expansion@>=2.0.0 <2.1.2: ^2.1.2
  multer: 2.2.0
